### ISSUE TITLE
Symfony 4.3 - No transport supports the given Messenger DSN "enqueue://default"

### ISSUE THREAD

**Issue by lsv** [sroze/messenger-enqueue-transport#73]
Im running my command

`bin/console messenger:consume amqp`

But Im getting this error

In TransportFactory.php line 42:
                                                                      
  No transport supports the given Messenger DSN "enqueue://default".

Everything worked perfect in Symfony 4.2

```yaml
# messenger.yaml
framework:
    messenger:
        transports:
            amqp: enqueue://default

        routing:
            '*': amqp
```

```yaml
# enqueue.yaml (with my database connection)
enqueue:
    default:
        transport: '%env(resolve:DATABASE_URL)%'
        client: ~
```

```json
"enqueue/dbal": "^0.9.8",
"enqueue/enqueue-bundle": "^0.9.8",
"sroze/messenger-enqueue-transport": "^0.3.0",
"symfony/messenger": "4.3.*",
```
