### ISSUE TITLE
It's not possible to pass consumer specific options from DSN

### ISSUE THREAD

**Issue by maks-rafalko** [sroze/messenger-enqueue-transport#88]
We use Kafka with https://github.com/php-enqueue/rdkafka transport and it's impossible to set a Consumer-specific options, in particular `group.id`.

There is only [global `group.id` ](https://php-enqueue.github.io/transport/kafka/#create-context) setting that adds the group **for all consumers** rather than on per-consumer basis.

Class `QueueInteropTransport` creates a consumer here:

https://github.com/sroze/messenger-enqueue-transport/blob/a707be977963a386c45a63e9e9a0d63a9eb4421c/QueueInteropTransport.php#L250-L257

And there is no way to send any options/settings except the `Destination` class, which is a `RdKafkaTopic` in our case.

What we would like to be able to do is to set settings that would be passed to the consumer constructor

https://github.com/php-enqueue/rdkafka/blob/2449f06c892656d598b1c8ab8ceb4a4ac848ab6c/RdKafkaContext.php#L114

Any hints how to do it with all these tiers layers of abstractions?

**Comment by Steveb-p** [comment]
Current workaround would be creating another `enqueue` entry with another Kafka configuration, and then selecting it by dsn, like: `enqueue://another`.

**Comment by maks-rafalko** [comment]
Yes, there are definitely many workarounds (we have overridden `RdFakfaContext` for this case). But let's think about what architecture changes needs to be done to allow passing consumer specific options.

Currently, interop interfaces does not allow to do it. E.g. `public function createConsumer(Destination $destination): Consumer;` - we can path only `destination` which is ` RdKafkaTopic`. No settings for consumer itself.

**Comment by rdotter** [comment]
@maks-rafalko we use the folowing enqueue config and works for multiple envs and multiple settings within global / topic setting for Kafka:
```
            dsn: 'kafka://%env(resolve:ENQUEUE_KAFKA_DSN_BROKER)%'
            global:
                metadata.broker.list: '%env(resolve:ENQUEUE_KAFKA_DSN_BROKER)%'
                group.id: app-id
                enable.auto.offset.store: 'false'
            topic:
                auto.offset.reset: beginning
```

**Comment by Nyholm** [comment]
Hm... If you want something "transport" specific, the best way to pass variables is to use `options`. 

```yaml

framework:
    messenger:
        transports:
            foobar: 
                dsn: '....'
                options: { group.id: custom-consumer-group }
```

These options is passed to the TransportFactory. We probably need some changes to that factory so it all will work.
